### ISSUE TITLE
Syntax Error: Missing '"'

### ISSUE THREAD

**Issue by gaiterjones** [fballiano/docker-magento2-cron#1]
Tying to test your update script to update the varnish VCL.

I can get the VCL from Varnish, the config edit is working but when I try and apply the new config the vcl.inline command is failing with a syntax error returned from the varnish server :

`Syntax Error: Missing '"'`

Any ideas what is causing the syntax error? If I export the generated vcl as txt and do

`varnishd -C -f new.vcl`

I don't get any errors, so the generated VCL seems to be valid.

**Comment by gaiterjones** [comment]
OK, I figured this one out myself, it's working now!

**Comment by fballiano** [comment]
is it something we should fix in the images? thanks!
